[build-system]
requires = ["setuptools >= 61.0.0",
    "build",
    "sphinx"]
build-backend = "setuptools.build_meta"

# https://packaging.python.org/en/latest/specifications/declaring-project-metadata/
[project]
name = "ai4copsec-restapi"
dynamic = ["version"]
description = "AI4COPSEC RESTAPI"
license = { file = "LICENSE" }
readme = "README.md"
keywords = ["ai4copsec", "monitor"]
authors = [
    { name = "Thomas Roehr", email = "roehr@simula.no" }
]
requires-python = ">=3.10"

maintainers = [
    { name = "Thomas Roehr", email = "roehr@simula.no" }
]

classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Development Status :: 3 - Alpha",
    "Operating System :: OS Independent",
    "Programming Lanugage :: Python :: 3.10",
    "Programming Lanugage :: Python :: 3.11",
    "Programming Lanugage :: Python :: 3.12",
    "License :: OSI Approved :: BSD License",
]

dependencies = [
    "ai4copsec@git+https://github.com/ai4copsec/ai4copsec-technological_bricks.git",
    "asyncpg",
    "aiosqlite",
    "cachetools",
    "fastparquet",
    "fastapi[standard]",
    "fastapi-cache2[memcache]",
    "fastapi_utils",
    "fastapi-pagination",
    "greenlet",
    "kafka-python>=2.2.15",
    "networkx",
    "numpy",
    "pandas",
    "prometheus-fastapi-instrumentator",
    "psutil",
    "pyarrow",
    "pydantic",
    "pydantic-settings",
    "pyjwt[crypto]",
    "pyyaml",
    "pyzmq",
    "psycopg2-binary",
    "python-snappy",
    "sqlalchemy",
    "sqlalchemy-schemadisplay",
    "tqdm",
    "typing_inspect",
    "uvicorn"
]

[project.urls]
homepage = "https://github.com/ai4copsec/ai4copsec-restapi"
documentation = "https://ai4copsec.github.io/ai4copsec-restapi"
repository = "https://github.com/ai4copsec/ai4copsec-restapi.git"

#[project.entry-points]

[project.optional-dependencies]

dev = [
    "isort",
    "jupyter-book<2",
    "pre-commit",
    "ruff",
    "sphinx-autoapi",
    "tox"
]

test = [
    "coverage",
    "httpx",
    "pytest",
    "pytest-asyncio",
    "pytest-console-scripts",
    "pytest-cov",
    "pytest-mock",
    "pydot",
    "tox"
]


[project.scripts]
ai4copsec-restapi = "ai4copsec.restapi.cli.main:run"

[tool.mypy]
ignore_missing_imports = true

[tool.setuptools]
    script-files = []

[tool.setuptools.package-data]
"ai4copsec.restapi" = [ "resources/**/*" ]

[tool.setuptools.dynamic]
version = { attr = "ai4copsec.restapi.__version__" }

[tool.coverage.run]
source = ["src"]

[tool.ruff]
line-length = 120

[tool.isort]
multi_line_output = 8

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"

[tool.ruff.lint.per-file-ignores]
"conftest.py" = ["E501"]
"test_gpu.py" = ["E501"]
