[tox]
name=ai4copsec-restapi
artifacts_dir={toxinidir}/artifacts
min_version = 4.0
env_list = py

[testenv]
extras =
    test

allowlist_externals =
    bash
    pytest
    docker
    echo

passenv =
    PYTEST_ARGS

commands =
    pytest --cov={[tox]name} \
           --cov-report=html:{[tox]artifacts_dir}/tests/ \
           --cov-report=term \
           --cov-report=xml:{[tox]artifacts_dir}/tests/cobertura-coverage.xml \
           {toxinidir}/tests/ai4copsec/ {env:PYTEST_ARGS:}

[testenv:build]
use_develop=True
deps =
    pyinstaller

allowlist_externals =
    pyinstaller
    bash
    rm

commands =
    bash -c "pyinstaller --onefile --distpath {toxinidir}/dist/$(uname -i) --name ai4copsec-restapi {toxinidir}/src/ai4copsec/restapi/cli/main.py"

[testenv:build-nuitka]
use_develop=True
deps =
    nuitka
    patchelf

allowlist_externals =
    export
    bash
    rm

commands =
    bash -c " \
        export NUITKA_BUILD_ARCH=$(python -c 'import platform; print(platform.machine())'); \
        nuitka --onefile --output-filename=ai4copsec-restapi --output-dir={toxinidir}/dist/$NUITKA_BUILD_ARCH {toxinidir}/src/ai4copsec/restapi/cli/main.py; \
    "

[testenv:build_docs]
skip_install = true
deps =
    jupyter-book
commands =
    python -m pip install pydot
    python -m pip install .[dev] -U
    jupyter book build docs
